name = "pog"
version = "3.3.0"
gleam = ">= 1.11.0"
licences = ["Apache-2.0"]
description = "A PostgreSQL database client for Gleam, based on PGO"

repository = { type = "github", user = "lpil", repo = "pog" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[documentation]
pages = [
  { title = "Solving SSL issues", path = "docs/solving-ssl-issues.html", source = "docs/solving-ssl-issues.md" },
]

[dependencies]
gleam_erlang = ">= 1.2.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.51.0 and < 2.0.0"
gleam_time = ">= 1.0.0 and < 2.0.0"
pgo = ">= 0.12.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
exception = ">= 2.0.0 and < 3.0.0"

[erlang]
# Starting an SSL connection relies on ssl application to be started.
extra_applications = ["ssl"]
